language: go
sudo: required

env:
  global:
    - ORACLE_COOKIE=sqldev
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE
    - PKG_CONFIG_PATH=$HOME/gopath/src/github.com/$TRAVIS_REPO_SLUG

before_install:
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh
  - >
    { echo "Name: oci8"; echo "Description: Oracle Call Interface"; echo "Version: 11.2";
      echo "Cflags: -I$ORACLE_HOME/rdbms/public";
      echo "Libs: -L$ORACLE_HOME/lib -Wl,-rpath,$ORACLE_HOME/lib -lclntsh";
    } | tee oci8.pc
  - go get github.com/golang/lint/golint
  - go get github.com/kisielk/errcheck

install: true

script:
  - go vet -x $(go list ./... | grep -v /vendor/)
  - $HOME/gopath/bin/golint -set_exit_status $(go list ./... | grep -v /vendor/)
  - $HOME/gopath/bin/errcheck $(go list ./... | grep -v /vendor/)
  - go test -v -coverprofile=coverage.txt -covermode=atomic $(go list ./... | grep -v /vendor/)

after_success:
  - bash <(curl -s https://codecov.io/bash)
